### ISSUE TITLE
Directory correction in the Install guide

### ISSUE THREAD

**Issue by rea987** [popsUlfr/Proton#1]
Greetings,

Recent versions of Mint (and perhaps Ubuntu) use `~/.steam` instead of `~/.local/share/Steam` for Steam client installations. Therefore, following lines should be provided as an option in the Install guide:

https://github.com/popsUlfr/Proton/releases

$ mkdir -p ~/.steam/compatibilitytools.d
$ cd ~/.steam/compatibilitytools.d

**Comment by popsUlfr** [comment]
Ok, thanks for the info. I added this information to the release.

**Comment by rea987** [comment]
It looks like Steam is installed to different directories depending on installation method. On my usual system, I installed Steam via Mint 19 repo package which ended up installing on `~/.steam`. However, to test Gallium Nine, I installed Mint 19.1 on an AMD laptop and installed Steam via Steam's own .deb installer which installed Steam on `~/.local/share/Steam`. I guess it would be better to offer both directories to users just to be safe.

**Comment by popsUlfr** [comment]
I making myself a note here to have a look at how proton's `make install` manages to detect the right path.

It's set by default to `STEAM_DIR := $(HOME)/.steam/root`

Could you confirm that

```
$ mkdir -p ~/.steam/root/compatibilitytools.d
$ cd ~/.steam/root/compatibilitytools.d
$ tar xf Proton_3.16-6_Gallium_Nine_Extras_0.1.1.tar.xz
```

gets the job done for most distro ? `root` links back to `~/.local/share/Steam` for me.
