### ISSUE TITLE
Wrong DXVK version

### ISSUE THREAD

**Issue by MikeGriniezakis** [popsUlfr/Proton#11]
![screenshot_20190201_222257](https://user-images.githubusercontent.com/34035338/52147646-0b57b200-2670-11e9-9bd1-71872f8036c8.png)
If you look at the top-left corner, you can see that the dxvk version is 0.90. I use the latest version proton 3.16-6 with the dxvk 0.96 from this fork and it says version 0.90.

**Comment by popsUlfr** [comment]
![20190201230627_1](https://user-images.githubusercontent.com/1030423/52152281-2c230600-2676-11e9-8c4e-d65971ad429c.jpg)

This is with 'Proton 3.16-6 Gallium Nine Extras 0.3.0' 

Also the first release I ever published here had DXVK 0.94, so it looks like something went wrong when installing the proton.

So, can you elaborate on how you installed it and selected it in Steam ?

**Comment by MikeGriniezakis** [comment]
It turns out steam selected proton 3.16-4 due to "valve testing" for dark souls 3 which overrode your custom proton version with dxvk 0.96. I checked it with the latest steam version which shows what version of proton is being used to run a game. So I tested it again, this time with forced proton it worked wonderfully.

**Comment by popsUlfr** [comment]
Nice, have fun ;)
