### ISSUE TITLE
No Proton 4.2-2?

### ISSUE THREAD

**Issue by tatsujb** [popsUlfr/Proton#14]
# Feature Request

Proton 4.2-2 version.

Love your work and I want to see this continue.

Steam moved proton version to 4.2-2
would you mind forking and add gallium 9 dx12 again?

pretty please? :)

really love your work

**Comment by rea987** [comment]
Winetricks and Protontricks have already added Gallium Nine, so there's not much pressure.

**Comment by tatsujb** [comment]
what's protontricks? wow it's really hard to stay ahead of the curb these days and I love that happening in linux for once!

I looked into [it](https://github.com/Matoking/protontricks), pretty cool! :D I'm probably going to drop your gallium-proton from my script : https://github.com/tatsujb/installFAFscript but I don't know that I can replace it with protontricks.

when you use protontricks can you add gallium to steam as a whole or can you only run games via protontricks.

I'm using a method where I run the game via steam's proton using the Run file steam generates when you add `PROTON_DUMP_DEBUG_COMMANDS=1` as a launch parameter to the game.

what I'm wondering is if I pre-emptively do some trickery with protontricks, would the Run file generated by steam launch the game with a gallium nine version of steam's proton or would I have to have my script edit the generate run file to point to protontricks instead?

**Comment by tatsujb** [comment]
apparently you could do it with 

```
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks.bash-completion
sudo mv winetricks /usr/bin
sudo mv winetricks.bash-completion /usr/share/bash-completion/completions/winetricks
python3 -m pip install --user pipx
~/.local/bin/pipx ensurepath
eval "$(cat .bashrc | tail -n +10)"
pipx install protontricks
pipx upgrade protontricks
protontricks 9420 galliumnine
```

where 9420 is your app id.

**Comment by crt0mega** [comment]
This doesn't work anymore, see [#3863 on ValveSoftware/Proton](https://github.com/ValveSoftware/Proton/issues/3863).

**Comment by tatsujb** [comment]
I don't personally see the point in gallium nine anymore.
