### ISSUE TITLE
Show Gallium Nine status

### ISSUE THREAD

**Issue by rea987** [popsUlfr/Proton#3]
# Feature Request
Show Gallium Nine status

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
A terminal output or log to show whether Gallium Nine is/was active or not

## Justification [optional] 
It is unclear if current build of Proton with Gallium Nine patches use native Direct3D or not

## Information
As some games show Steam Overlay and some don't, I suspect that the games that do show Steam Overlay fails to utilize Gallium Nine. After all, native Steam client isn't supposed to use Direct3D 9 natively. As **wine-d3d9-staging** does show Native Direct3D 9 status, same would be beneficial for this project.

![screen](https://user-images.githubusercontent.com/1547646/50408237-1ceba580-07f8-11e9-8d44-5320255d7c23.png)

https://wiki.ixit.cz/d3d9

## References [optional] 

https://github.com/popsUlfr/Proton/issues/2#issuecomment-449633390
https://github.com/popsUlfr/Proton/issues/2#issuecomment-449777838

**Comment by andy-d1969** [comment]
You can create a file <code>~/.steam/compatibilitytools.d/Proton_3.16-5_Gallium_Nine_Extras_0.1.1/user_settings.py</code> with the following content:
<code>user_settings = {                                                                                                                                                             
    "WINEDEBUG": "+d3d9,+d3dadapter9"                                                                                                                                         
} </code>
Then add <code>PROTON_LOG=1</code> to the launch options of the game. This will dump a log file to your home directory containing <code>Native Direct3D 9 is active.</code> if gallium nine works.
If you want to see the performance you can add <code>GALLIUM_HUD=simple,fps</code> to the launch options.

**Comment by rea987** [comment]
https://github.com/popsUlfr/Proton/issues/3#issuecomment-449839486

Thanks @andy-d1969, that worked! As a side note, I confirm that Steam Overlay doesn't work when Gallium Nine is active. So, if you see Steam Overlay functioning properly, then Gallium Nine certainly doesn't. As I am unsure if Steam Overlay issue is fixable, I can take it as an unintended workaround for Gallium Nine status.

**Comment by popsUlfr** [comment]
For the steam overlay to work, gallium nine would need to be wrapped in an opengl context. I don't know if it is possible but in theory one would need to intercept the d3d9 Present call and send the backbuffer to the opengl swapchain call. This is sure to cost some performance though.
